# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"
group :development do
  gem 'rubocop', require: false # 追加
  gem 'rubocop-performance', require: false # 追加
  gem 'rubocop-rails', require: false # 追加
  gem 'rubocop-rspec' # 追加
end
